name: Wine Valve exp bleeding edge Pacman CI

on:
  schedule:
    - cron:  '45 8,20 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v7
      - name: Compile
        run: |
          pacman -Syu --noconfirm base-devel sudo
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R . && cd wine-tkg-git
          sed -i 's/LOCAL_PRESET=""/LOCAL_PRESET="valve-exp-bleeding"/' customization.cfg
          sed -i 's/wayland_driver="false"/wayland_driver="true"/' customization.cfg
          # Wine-TkG uses "wow64" to disable the separate 32-bit build.
          printf '_NOLIB32="wow64"\n' >> wine-tkg-profiles/advanced-customization.cfg
          su user -c "yes|PKGDEST=/tmp/wine-tkg makepkg --noconfirm -s"

      - name: Archive the artifacts
        uses: actions/upload-artifact@v7
        with:
          name: wine-tkg-build
          path: /tmp/wine-tkg
